#SERVER
server:
  port: 8081

#SPRING
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${SQL_DB_PASSWORD}
    url: ${SQL_DB_HOST}:${SQL_DB_PORT}/postgres
    username: ${SQL_DB_USERNAME}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update

#LOGGING
logging:
  level:
    root: INFO

#OPENAPI
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui



