server:
  port: 8082

spring:
  output:
    ansi:
      enabled: ALWAYS
  h2:
    console:
      enabled: true
      path: /h2
#  datasource:
#    url: jdbc:h2:file:~/test
#    username: sa
#    password: sa
#    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
custom:
  logging:
    logPrefix: BASE_API

#LOGGING
#logging:
#  level:
#    root: INFO
#    com:
#      projecto:
#        baseapi: TRACE
#  pattern:
#    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){green} %clr([%level]){magenta}  %c{1.} [%t] : %m%n"
#    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){green} %clr([%level]){magenta}  %c{1.} [%t] : %m%n"
#  file:
#    name : BaseApi.log

security:
  jwt:
    secret-key: ${security.jwt.secret-key}
    expiration-time: ${security.jwt.expiration-time}
  # 1h in millisecond
#  security.jwt.expiration-time=3600000